### ISSUE TITLE
Good plugin, but the price is a bit steep?

### ISSUE THREAD

**Issue by MostHated** [beansoft/iscratch-support#1]
Hey there,
    I just wanted to say, I tried out the iScratch plugin and I thought it was pretty neat, so I was going to buy it, but then I saw it was $30? I would definitely buy it if it were $5-$10 like most other plugins, but I just feel that considering scratch functionality already exists in the editor, that this is a bit much.

Thanks,
-MH

**Comment by beansoft** [comment]
Hi dear friend,
    This plugin's main purpose is like something with Jetbrains' Code Notes, or Code Reading Notes, just like https://plugins.jetbrains.com/search?search=Code%20Notes shows. But after trying their plugin, the doesn't fit my need, so  I spend almost three months spare time(from May to August) to build my ones. But as you can see, the most Notes plugins(include Jetbrains), doesn't get too much download at all, so this plugin is mainly used by myself.
    Anyway, i'll try to adjust down the price but due to the poor download count, i'm not sure what will happen.


    If you ready wanna to spend $10 to buy it yearly, i'll give you a coupon at that price, please mail to me ***@***.***), and i'll send to you.

**Comment by MostHated** [comment]
I appreciate the reply. I would be interested in doing that, but unfortunately, the email address seems to have been redacted?  This is how it appears:

![](https://i.imgur.com/Fnxj6ue.png)

**Comment by beansoft** [comment]
Hi, please check the plugin home page:
https://plugins.jetbrains.com/plugin/17501-iscratch-notes


and there is my vendor mail address.


Really hate Microsoft to do this, filter out the emails...

**Comment by beansoft** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }

**Comment by MostHated** [comment]
Hey again. The tool is coming along very well. :+1: 

 I had a question, though. It seems that not all of the file types are available for assignment to a note. Is there something special I have to do to make them show up? 

An example is the "Dockerfile" type. You can see below, the file type is known and seen in the filesystem tree and you can see all proper highlighting in the text area, as well as the custom commands in the editor gutter.

![](https://i.imgur.com/xy3qPzN.png)


But then it does not seem to be able to assign it to the Dockerfile type within my notes "Change Language" section.


![](https://i.imgur.com/dW0Itqc.png)

Is this a bug, or working as intended?
Thanks,
-MH

**Comment by beansoft** [comment]
The languages are filtered out like something in IDEA like File Language that normally have an extension, but DOCKERFILE doesn't have one. i'll trying to take a look at if i can create a editor for languages that have no extension.

**Comment by beansoft** [comment]
Please try install this link: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=155529 , I've tested under from 2020.3 to 2022.1 EAP. Now you can add dockerfile content to notes.

**Comment by beansoft** [comment]
Please update to this one: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=155683
the old one have problems open the settings page to change the editor font or database path.

**Comment by MostHated** [comment]
Ok, thanks, I will try this out here as soon as I get a chance and report back.

**Comment by MostHated** [comment]
Looks good. :+1: 

Thanks, I do appreciate it.

![](https://i.imgur.com/A6iV6TB.png)

**Comment by beansoft** [comment]
Please update to the latest version:  https://plugins.jetbrains.com/plugin/17501-notes/versions
2022.1.0
-Fix Issue #1, support some languages without default extension such as Dockerfile
-Fix Issue #7, Crashes with latest version of Webstorm 2021.1
-Fix focus traversal issue when pressing tab key can't move the code editor area
-Fix some window focus issue when work with multi-project
-New: Support modify editor, tree and list font in the Notes window, click Settings > Tools > Notes
-New: Toggle to hide editor red errors in the Notes window
-New: Add trash bin, can move note to trash, restore, delete permanently or empty the trash
-New: Paste Html from Clipboard to Markdown, try copy something from Slack or web browser
-Improve: Save and restore the editing note after project opened
-New: Allow locate to note in the editor's note edit dialog
-Improve: Add context menu to list and tree
