### ISSUE TITLE
Window focus problem with AsciiDoc plugin

### ISSUE THREAD

**Issue by RayOffiah** [beansoft/iscratch-support#2]
Hi there. I'm using the plugin with the AsciiDoc plugin on Webstorm.

There's an odd problem when I am using the iScratch tool window with an AsciiDoc file. Although the Asciidoc preview and the toolbar are rendered correctly, the buttons on the toolbar (Italic, Bold etc) get applied to the main editor window, not the toolbar.
<img width="1663" alt="2021-12-09_08-50-41" src="https://user-images.githubusercontent.com/77050471/145364910-a167f8bd-7868-4c8d-86ca-2711bd81b57f.png">

**Comment by beansoft** [comment]
Could you please take a screenshot for me?

**Comment by RayOffiah** [comment]
How about this?
<img width="1797" alt="2021-12-09_16-04-42" src="https://user-images.githubusercontent.com/77050471/145432476-2c6c8687-a054-4c4e-b41b-aaee8cfdb584.png">

**Comment by beansoft** [comment]
The first EAP fix is in review by Jetbrains, please have a try before it's published:

https://plugins.jetbrains.com/plugin/download?rel=true&updateId=149883

Download and install from disk.

**Comment by RayOffiah** [comment]
Yep, that's fixed it. Thanks!
