### ISSUE TITLE
从源代码跳转到笔记是不是只支持不选中代码的笔记?

### ISSUE THREAD

**Issue by xiaoyoucheng** [beansoft/iscratch-support#29]
想要源代码跳转到笔记的功能，后面发现好像只有 不选中代码，选择行号记录的笔记才能点击⭐在ALT+G进行跳转。
还是说只是我没有找到怎么使用跳转功能?
毕竟支持从笔记跳转到源代码，我觉得反过来应该也可以，所以来这里问一下。

**Comment by beansoft** [comment]
这块目前只能这么跳转。非常感谢你的建议，下一版本将会支持鼠标右键点击直接跳转打开笔记功能。

**Comment by beansoft** [comment]
新版已经发布，鼠标右键点击编辑器笔记图标 - 定位笔记，欢迎尝试
