### ISSUE TITLE
Feature Request: URL paths should be relative

### ISSUE THREAD

**Issue by huyz** [beansoft/iscratch-support#58]
I often my project around the filesystem.  This would break all the URLs since they have absolute paths.
Just as with the rest of IntelliJ, the paths should be relative to the project root.

**Comment by beansoft** [comment]
Thank you for your suggestion, a new big edition is in progress, which will support project-level notes.

**Comment by beansoft** [comment]
Please don't close it, I need to track it.

**Comment by beansoft** [comment]
Already released.
