### ISSUE TITLE
Suggestion: Add a trash bin

### ISSUE THREAD

**Issue by RayOffiah** [beansoft/iscratch-support#6]
When deleting a document or a folder, it would be nice if you could put them into a trash bin for retrieving later if you change your mind.

Would also need an 'empty trash' function.

**Comment by beansoft** [comment]
that's a great idea, first plan is to make a note deleted to recycle bin. yet need some time to implement this. May be two weeks.

**Comment by beansoft** [comment]
Hi, the version contains recycle bin is pending Jetbrain's approve. Please try it before released:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=156035

2022.1.0-EAP
-Fix Issue #1, support some languages without default extension such as Dockerfile
-Fix Issue #7, Crashes with latest version of Webstorm 2021.1
-New: Support modify editor, tree and list font in the Notes window, click Settings > Tools > Notes
-New: Toggle to hide editor red errors in the Notes window
-New: Add trash bin, can move note to trash, restore, delete permanently or empty the trash
-New: Paste Html from Clipboard to Markdown, try copy something from Slack or web browser
-Improve: Save and restore the editing note after project opened
-Improve: Allow locate to note in the editor's note edit dialog

**Comment by RayOffiah** [comment]
Looks good!

I have a couple of suggestions:

Enable drag and drop.

When move an item to another folder, I would probably keep the focus on the current location instead of switching to the folder you've just moved the item into. I don't think anyone really wants to look at the contents of the bin, even if they've just moved an item into it.

**Comment by beansoft** [comment]
Drag and drop will be added later, as I'm researching on the possbility to using Evernote as a cloud storage, the Luna vocation will soon be over in 3 days.

I've improved the trash bin when delete or restore items to/from it.

You can have a try before it's finally released:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=156275

2022.1.0
-Fix Issue #1, support some languages without default extension such as Dockerfile
-Fix Issue #7, Crashes with latest version of Webstorm 2021.1
-Fix focus traversal issue when pressing tab key can't move the code editor area
-Fix some window focus issue when work with multi-project
-New: Support modify editor, tree and list font in the Notes window, click Settings > Tools > Notes
-New: Toggle to hide editor red errors in the Notes window
-New: Add trash bin, can move note to trash, restore, delete permanently or empty the trash
-New: Paste Html from Clipboard to Markdown, try copy something from Slack or web browser
-Improve: Save and restore the editing note after project opened
-New: Allow locate to note in the editor's note edit dialog
-Improve: Add context menu to list and tree
