### ISSUE TITLE
Crashes with latest version of Webstorm

### ISSUE THREAD

**Issue by RayOffiah** [beansoft/iscratch-support#7]
WebStorm 2022.1 EAP
Build #WS-221.3427.92, built on January 27, 2022
WebStorm EAP User
Expiration date: February 26, 2022
Runtime version: 11.0.13+8-b1890.4 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (221.3427.87)
    name.kropp.intellij.makefile (221.3427.93)
    com.intellj.plugin.SpringBootBannerPlugin (0.2.9)
    com.intellij.ideolog (203.0.27.0)
    org.asciidoctor.intellij.asciidoc (0.36.18)
    com.github.beansoft.iscratch (2021.1.1)
    String Manipulation (8.25.203.5981.1)
    Shifter (1.9.6)
    PlantUML integration (5.10.0)
    org.rust.lang (0.4.163.4378-213)
    com.intellij.database (221.3427.92)
    izhangzhihao.rainbow.brackets (6.21)
    com.github.shiraji.yaemoji (1.0.7)
<img width="1965" alt="2022-01-30_16-40-30" src="https://user-images.githubusercontent.com/77050471/151708664-742da9e2-e0a5-475a-b89b-1593b2eb7de0.png">

**Comment by beansoft** [comment]
I've fixed this issue, and will upload later with some other features. Today I will upload an EAP release and send a link to you.

**Comment by beansoft** [comment]
Please try install this link: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=155529 , I've tested under from 2020.3 to 2022.1 EAP.

**Comment by RayOffiah** [comment]
Yes. This has fixed the problem. Thanks.

**Comment by beansoft** [comment]
Please update to this one: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=155683
the old one have problems open the settings page to change the editor font or database path.
