### ISSUE TITLE
Suggestions: Path of the bookmark next to note name and go to line when active note

### ISSUE THREAD

**Issue by erbear** [beansoft/iscratch-support#8]
Hi there, 
I love the app however it's missing features that could be really helpful while working. I use the app mainly to add bookmarks in code with todo. When I work I use those bookmarks to skip through the code and files. I would really appreciate information what file is signed to note item next to the note title in notes list. The navigation would be much easier that way. 

The navigation would be even easier if I could skip to the file when selecting the note. But it not so necessary, first feature is more helpful. 

Is this something you can think about?

**Comment by beansoft** [comment]
Thank you to try the Notes plugin. I’ll create a version with url displayed under the title and allow double click(or press Enter key) to directly open the linked file. After it’s done I’ll send you a EAP version for a test. Any suggestion is welcome.

**Comment by erbear** [comment]
Wow! It would be great 😍 
I am using single row view, can the url be displayed also next to the title? 
One point about the skiping file feature - it is already possible to setup enter to skip to file because I can setup the shortcut. One problem with this shortcut is that it is not limited to scope of notes view but it is available globally and using enter in editor causes skipping to note. Also it loses focus on the notes view after using this shortcut. Maybe limiting this shortcut to notes view only and not loosing focus would make this feature easier to implement. 

If suggestions are welcome there is one more thing I would appreciate if it's not complicated to implement. It would be great to have custom order of the notes, you know, drag and drop notes to change the order of items on list. However it is just nice to have so no pressure. 

thank you so much for taking this suggestions. I am paying user to support development. One more note - you can use the tool even after trial period ends, this is some kind of bug probably. 

Thanks again!

**Comment by beansoft** [comment]
For the last one "you can use the tool even after trial period ends", I've heard that the license check is not done after the IDE starts up in some IDEA versions, so I'd like to know what situation is it? Which IDEA version you are using and how to reproduce it? Just install and try the plugin?

**Comment by beansoft** [comment]
I've created a test version: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=167062 , you can download and have a try:
Display linked source code file name and supports key navigation: using up/down key to change, press Enter key
        or double click to open the linked file, press Esc key to Go to main editor.

**Comment by erbear** [comment]
Here is the version of my rubymine: 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3940656/162605249-9b08073b-1b19-4993-9c03-ba8a0c904a97.png">

Yea, I was just using the plugin and there were notifications that the trial will end. However after that point in time nothing happened and I was able to use the plugin normally. 

About the test version - skipping files works great :) Double click or enter works and the focus does not change to editor which is great :) 
About the source code file name - it works too, however, name only is not enough information, path is important in this situation as well. You know I have many services that are named index, create, show and the path would give me more context what this file is about. 

Thanks for those features anyway. The plugin is already more helpful :)

**Comment by beansoft** [comment]
I've create a updated version for the license check issue and the file name display, please try before it's released:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=167138

**Comment by erbear** [comment]
I have been testing new functionalities today and they are sooo useful. However, I didn't test licence check because I have paying account already. 

Thank you again for implementing those features :)

**Comment by beansoft** [comment]
Thx for your test. I've found a way to reproduce the license issue, just from Help -> Register, remove the license, and restart the IDE, enable the plugin again, then restart, then the plugin is working again, I've fixed that issue. BTW, the new version has released, please remove this test version and install from your IDE's plugin page again.
